# Generated by Django 6.0.2 on 2026-02-10 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('area_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'In the Field'), ('HARVESTED', 'Harvested & Sold')], default='ACTIVE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('date', models.DateField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cropcycle')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('total_land_area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cropcycle',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.farmerprofile'),
        ),
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_receipt', models.ImageField(blank=True, null=True, upload_to='sales/')),
                ('date_sold', models.DateField()),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cropcycle')),
            ],
        ),
    ]
