# Generated by Django 6.0.2 on 2026-02-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropcycle',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yield',
            name='quantity_produced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
