# Generated by Django 5.2.5 on 2026-02-11 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cropcycle_created_at_expense_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='has_kcc',
            field=models.BooleanField(default=False, help_text='Has Kisan Credit Card'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='SchemeRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('eligibility_criteria', models.TextField()),
                ('link', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_recommendations', to='core.farmerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
